name: Deploy-GH-Pages

on: 
  push:
    branches: 
      - master

jobs:
  build-deploy:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        npm install
        npm run build
    - uses: alex-page/blazing-fast-gh-pages-deploy@v1.1.0
      with:
          repo-token: ${{ secrets.GH_PAT }}
          site-directory: "dist"
    - name: Deploy
      run: echo Deploying
